# Generated by Django 5.2 on 2025-04-16 21:27

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesgv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lgvpage',
            name='body',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
