# Generated by Django 5.2 on 2025-04-16 23:07

import markdownfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesgv', '0003_siteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='lgvpage',
            name='body_html',
            field=markdownfield.models.RenderedMarkdownField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='body_html',
            field=markdownfield.models.RenderedMarkdownField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lgvpage',
            name='body',
            field=markdownfield.models.MarkdownField(rendered_field='body_html'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='body',
            field=markdownfield.models.MarkdownField(rendered_field='body_html'),
        ),
    ]
