# Generated by Django 5.2 on 2025-04-16 23:15

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesgv', '0004_lgvpage_body_html_siteconfiguration_body_html_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lgvpage',
            name='body_html',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='body_html',
        ),
        migrations.AlterField(
            model_name='lgvpage',
            name='body',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='body',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
