# Generated by Django 5.2 on 2025-04-20 14:25

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='WagtailLgvSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Footer1', wagtail.fields.RichTextField()),
                ('Footer2', wagtail.fields.RichTextField()),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='favicon/')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
