# Generated by Django 5.2 on 2025-04-20 14:30

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_lgv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wagtaillgvsettings',
            name='Footer1',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wagtaillgvsettings',
            name='Footer2',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wagtaillgvsettings',
            name='maintenance_mode',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
