# Generated by Django 5.2 on 2025-04-20 14:56

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_lgv', '0002_alter_wagtaillgvsettings_footer1_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='WagtailLgvHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, null=True)),
                ('body', wagtail.fields.RichTextField(blank=True, null=True)),
                ('section1', wagtail.fields.RichTextField(blank=True, null=True)),
                ('section2', wagtail.fields.RichTextField(blank=True, null=True)),
                ('section3', wagtail.fields.RichTextField(blank=True, null=True)),
                ('ghost_post_tag', models.SlugField(blank=True, null=True)),
                ('description', wagtail.fields.RichTextField(blank=True, null=True)),
                ('header_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
