# Generated by Django 5.2 on 2025-04-16 22:35

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coolgv', '0002_alter_lgvpage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Site Name', max_length=255)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('body', markdownx.models.MarkdownxField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
