# Generated by Django 5.2 on 2025-04-18 06:12

import gdv1.models
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gdv1Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', gdv1.models.TitleMarkdownxField()),
                ('body', markdownx.models.MarkdownxField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', gdv1.models.TitleMarkdownxField(default='Titre du site', max_length=255)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('body', markdownx.models.MarkdownxField(null=True)),
                ('section1', markdownx.models.MarkdownxField(null=True)),
                ('section2', markdownx.models.MarkdownxField(null=True)),
                ('section3', markdownx.models.MarkdownxField(null=True)),
                ('intro', markdownx.models.MarkdownxField(null=True)),
                ('ghost_post_tag', models.SlugField(null=True)),
                ('footer1', markdownx.models.MarkdownxField(null=True)),
                ('footer2', markdownx.models.MarkdownxField(null=True)),
                ('description', markdownx.models.MarkdownxField(null=True)),
                ('favicon', models.ImageField(null=True, upload_to='favicon/')),
            ],
            options={
                'verbose_name': 'Configuration du site',
            },
        ),
    ]
