# Generated by Django 5.2 on 2025-04-17 09:00

import gdv1.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gdv1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='title',
            field=gdv1.models.TitleMarkdownxField(default='Titre du site', max_length=255),
        ),
    ]
