# Generated by Django 5.2 on 2025-04-17 12:07

import django.db.models.deletion
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdv1', '0002_alter_siteconfiguration_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gdv1HomePage',
            fields=[
                ('gdv1page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gdv1.gdv1page')),
                ('section1', markdownx.models.MarkdownxField()),
                ('section2', markdownx.models.MarkdownxField()),
                ('section3', markdownx.models.MarkdownxField()),
                ('intro', markdownx.models.MarkdownxField()),
                ('ghost_post_tag', models.SlugField(null=True)),
            ],
            bases=('gdv1.gdv1page',),
        ),
    ]
