# Generated by Django 5.2 on 2025-04-18 06:35

import django.core.validators
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdv1', '0002_siteconfiguration_favicon_svg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='body',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='favicon/'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='favicon_svg',
            field=models.FileField(null=True, upload_to='favicon/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])]),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='footer1',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='footer2',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='intro',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='section1',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='section2',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='section3',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
