# Generated by Django 5.2 on 2025-04-17 12:12

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gdv1', '0003_gdv1homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer1',
            field=markdownx.models.MarkdownxField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer2',
            field=markdownx.models.MarkdownxField(default=''),
            preserve_default=False,
        ),
    ]
