# Generated by Django 5.2 on 2025-04-17 12:13

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gdv1', '0004_siteconfiguration_footer1_siteconfiguration_footer2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdv1homepage',
            name='intro',
            field=markdownx.models.MarkdownxField(null=True),
        ),
        migrations.AlterField(
            model_name='gdv1homepage',
            name='section1',
            field=markdownx.models.MarkdownxField(null=True),
        ),
        migrations.AlterField(
            model_name='gdv1homepage',
            name='section2',
            field=markdownx.models.MarkdownxField(null=True),
        ),
        migrations.AlterField(
            model_name='gdv1homepage',
            name='section3',
            field=markdownx.models.MarkdownxField(null=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='body',
            field=markdownx.models.MarkdownxField(null=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='description',
            field=markdownx.models.MarkdownxField(null=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='footer1',
            field=markdownx.models.MarkdownxField(null=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='footer2',
            field=markdownx.models.MarkdownxField(null=True),
        ),
    ]
