# Generated by Django 5.2 on 2025-04-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdv1', '0004_alter_siteconfiguration_favicon_svg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='favicon_svg',
            field=models.FileField(blank=True, null=True, upload_to='favicon/'),
        ),
    ]
