# Generated by Django 5.2 on 2025-04-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdv1', '0005_alter_siteconfiguration_favicon_svg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='ghost_post_tag',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
