# Generated by Django 5.2 on 2025-04-17 12:20

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdv1', '0005_alter_gdv1homepage_intro_alter_gdv1homepage_section1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='ghost_post_tag',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='intro',
            field=markdownx.models.MarkdownxField(null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='section1',
            field=markdownx.models.MarkdownxField(null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='section2',
            field=markdownx.models.MarkdownxField(null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='section3',
            field=markdownx.models.MarkdownxField(null=True),
        ),
        migrations.DeleteModel(
            name='Gdv1HomePage',
        ),
    ]
