# Generated by Django 5.2 on 2025-04-18 06:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdv1', '0006_alter_siteconfiguration_ghost_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='favicon_svg',
            field=models.FileField(blank=True, null=True, upload_to='favicon/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])]),
        ),
    ]
