# Generated by Django 5.2 on 2025-04-19 18:07

import django.core.validators
import lgv.models
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LgvPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', lgv.models.TitleMarkdownxField()),
                ('body', markdownx.models.MarkdownxField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', lgv.models.TitleMarkdownxField(default='Titre du site', max_length=255)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('body', markdownx.models.MarkdownxField(blank=True, null=True)),
                ('section1', markdownx.models.MarkdownxField(blank=True, null=True)),
                ('section2', markdownx.models.MarkdownxField(blank=True, null=True)),
                ('section3', markdownx.models.MarkdownxField(blank=True, null=True)),
                ('intro', markdownx.models.MarkdownxField(blank=True, null=True)),
                ('ghost_post_tag', models.SlugField(blank=True, null=True)),
                ('footer1', markdownx.models.MarkdownxField(blank=True, null=True)),
                ('footer2', markdownx.models.MarkdownxField(blank=True, null=True)),
                ('description', markdownx.models.MarkdownxField(blank=True, null=True)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='favicon/')),
                ('favicon_svg', models.FileField(blank=True, null=True, upload_to='favicon/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])])),
            ],
            options={
                'verbose_name': 'Configuration du site',
            },
        ),
    ]
